import type { BatterySizeClusterConfig } from "@/lib/battery-sizes/types";

export const BATTERY_SIZE_CLUSTERS: BatterySizeClusterConfig[] = [
  {
    code: "619",
    hubPath: "/619-car-battery",
    displayName: "619 Car Battery",
    headTerm: "619 car battery",
    brands: ["willard", "exide", "eco_plus", "power_plus"],
    specs: {
      voltage: "12V",
      ahRange: "42–43Ah",
      ccaRange: "314–325 CCA",
      dimensions: "207 × 175 × 175 mm",
      weight: "11.3–11.5 kg",
      terminalLayout:
        "Standard automotive (positive left, negative right on most SA fitments)",
      technology: "Maintenance-free SMF (flooded)",
      warrantyWillard: "25 months",
      warrantyExide: "24 months",
    },
    vehicleFitments: [
      "Toyota Tazz",
      "VW Polo Vivo",
      "Opel Corsa",
      "Suzuki Swift",
      "Ford Figo",
      "Hyundai i10 / i20 (selected models)",
    ],
    shelfPriceRanges: {
      midas: "R 1 200 – R 1 350",
      goldwagen: "R 1 180 – R 1 320",
      online: "R 1 100 – R 1 300",
    },
  },
  {
    code: "628",
    hubPath: "/628-car-battery",
    displayName: "628 Car Battery",
    headTerm: "628 car battery",
    brands: ["willard", "exide", "eco_plus", "power_plus"],
    specs: {
      voltage: "12V",
      ahRange: "48–55Ah",
      ccaRange: "335–520 CCA",
      dimensions: "207 × 175 × 190 mm",
      weight: "12–13 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyWillard: "25 months",
      warrantyExide: "24 months",
    },
    vehicleFitments: [
      "Toyota Corolla",
      "Honda Ballade",
      "Nissan Almera",
      "Hyundai Grand i10",
      "Renault Clio",
      "Suzuki Swift (selected models)",
    ],
    shelfPriceRanges: {
      midas: "R 1 350 – R 1 500",
      goldwagen: "R 1 320 – R 1 480",
      online: "R 1 250 – R 1 450",
    },
  },
  {
    code: "646",
    hubPath: "/646-car-battery",
    displayName: "646 Car Battery",
    headTerm: "646 car battery",
    brands: ["willard", "exide", "eco_plus", "power_plus"],
    specs: {
      voltage: "12V",
      ahRange: "55–60Ah",
      ccaRange: "380–550 CCA",
      dimensions: "242 × 175 × 190 mm",
      weight: "13–14 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyWillard: "25 months",
      warrantyExide: "24 months",
    },
    vehicleFitments: [
      "VW Golf",
      "Ford Fiesta ST",
      "Nissan NP200",
      "Renault Sandero",
      "Toyota Yaris",
      "Larger compact hatchbacks",
    ],
    shelfPriceRanges: {
      midas: "R 1 600 – R 1 850",
      goldwagen: "R 1 550 – R 1 800",
      online: "R 1 500 – R 1 750",
    },
  },
  {
    code: "652",
    hubPath: "/652-car-battery",
    displayName: "652 Car Battery",
    headTerm: "652 car battery",
    brands: ["willard", "exide", "eco_plus", "power_plus"],
    specs: {
      voltage: "12V",
      ahRange: "70–75Ah",
      ccaRange: "590–660 CCA",
      dimensions: "278 × 175 × 190 mm",
      weight: "17–19 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyWillard: "25 months",
      warrantyExide: "24 months",
    },
    vehicleFitments: [
      "Toyota Hilux",
      "Ford Ranger",
      "Isuzu KB",
      "Nissan Navara (selected models)",
      "Midsize bakkies",
      "Large SUVs",
    ],
    shelfPriceRanges: {
      midas: "R 1 850 – R 2 200",
      goldwagen: "R 1 800 – R 2 150",
      online: "R 1 750 – R 2 100",
    },
  },
  {
    code: "668",
    hubPath: "/668-car-battery",
    displayName: "668 Car Battery",
    headTerm: "668 car battery",
    brands: ["willard", "exide", "eco_plus", "power_plus"],
    specs: {
      voltage: "12V",
      ahRange: "80–85Ah",
      ccaRange: "590–715 CCA",
      dimensions: "315 × 175 × 190 mm",
      weight: "19–21 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyWillard: "25 months",
      warrantyExide: "24 months",
    },
    vehicleFitments: [
      "Premium SUVs",
      "Toyota Fortuner (selected models)",
      "Large diesel engines",
      "Heavy-duty petrol SUVs",
      "Land Cruiser Prado (selected)",
    ],
    shelfPriceRanges: {
      midas: "R 2 500 – R 2 900",
      goldwagen: "R 2 450 – R 2 850",
      online: "R 2 350 – R 2 800",
    },
  },
  {
    code: "658",
    hubPath: "/658-car-battery",
    displayName: "658 Car Battery",
    headTerm: "658 car battery",
    brands: ["willard", "exide", "eco_plus", "power_plus"],
    specs: {
      voltage: "12V",
      ahRange: "90–98Ah",
      ccaRange: "630–820 CCA",
      dimensions: "355 × 175 × 190 mm",
      weight: "22–25 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyWillard: "25 months",
      warrantyExide: "24 months",
    },
    vehicleFitments: [
      "Toyota Fortuner",
      "Large SUVs",
      "Diesel bakkies",
      "Toyota Land Cruiser",
      "Heavy-duty 4x4s",
    ],
    shelfPriceRanges: {
      midas: "R 2 600 – R 3 000",
      goldwagen: "R 2 550 – R 2 950",
      online: "R 2 450 – R 2 900",
    },
  },
  {
    code: "657",
    hubPath: "/657-car-battery",
    displayName: "657 Car Battery",
    headTerm: "657 car battery",
    brands: ["eco_plus", "power_plus"],
    valueTierOnly: true,
    hubIntro:
      "Value-tier 657 batteries from Eco Plus and Power Plus — ideal when you need reliable fitment without premium-brand pricing.",
    specs: {
      voltage: "12V",
      ahRange: "72Ah",
      ccaRange: "620–630 CCA",
      dimensions: "278 × 175 × 190 mm",
      weight: "17–18 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyValue: "12 months",
    },
    vehicleFitments: [
      "Mid-size commercial vehicles",
      "Selected SUVs",
      "Toyota Hilux (budget replacement)",
      "Ford Ranger (value option)",
    ],
    shelfPriceRanges: {
      midas: "R 1 400 – R 1 650",
      goldwagen: "R 1 350 – R 1 600",
      online: "R 1 300 – R 1 550",
    },
  },
  {
    code: "616",
    hubPath: "/616-car-battery",
    displayName: "616 Car Battery",
    headTerm: "616 car battery",
    brands: ["eco_plus", "power_plus"],
    valueTierOnly: true,
    hubIntro:
      "Affordable 616 compact-car batteries from Eco Plus and Power Plus — perfect for older city cars and budget commuters.",
    specs: {
      voltage: "12V",
      ahRange: "36Ah",
      ccaRange: "335–360 CCA",
      dimensions: "207 × 175 × 175 mm",
      weight: "10–11 kg",
      terminalLayout: "Standard automotive",
      technology: "Maintenance-free SMF (flooded)",
      warrantyValue: "12–24 months",
    },
    vehicleFitments: [
      "Smaller compacts",
      "Older city cars",
      "Entry-level hatchbacks",
      "Light commuter vehicles",
    ],
    shelfPriceRanges: {
      midas: "R 900 – R 1 100",
      goldwagen: "R 850 – R 1 050",
      online: "R 800 – R 1 000",
    },
  },
];

export function getClusterConfig(
  code: string
): BatterySizeClusterConfig | undefined {
  return BATTERY_SIZE_CLUSTERS.find((cluster) => cluster.code === code);
}

export function getAllClusterConfigs(): BatterySizeClusterConfig[] {
  return BATTERY_SIZE_CLUSTERS;
}
