window.ABM_PRODUCTS = [
  {
    id: 1,
    brand: "Exide",
    sku: "646CE",
    title: "Exide 646CE",
    price: "R 1 900.00",
    capacity: "58Ah",
    cranking: "451 CCA",
    warranty: "24-Month Warranty",
    tech: "Lead Acid",
    fits: "Sedans, SUVs & Light Commercial",
    badge: "IN STOCK",
    phone: "010 109 6211",
    imageUrl:
      "https://images.unsplash.com/photo-1621570273892-7104b2b29598?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 2,
    brand: "Willard",
    sku: "652",
    title: "Willard 652",
    price: "R 2 150.00",
    capacity: "70Ah",
    cranking: "600 CCA",
    warranty: "24-Month Warranty",
    tech: "Lead Acid",
    fits: "Hilux, bakkies & SUVs",
    badge: "IN STOCK",
    phone: "010 109 6211",
    imageUrl:
      "https://images.unsplash.com/photo-1605215705350-f8f413bf28dc?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: 3,
    brand: "Exide",
    sku: "AGM70",
    title: "Exide AGM70",
    price: "R 3 450.00",
    capacity: "70Ah",
    cranking: "760 CCA",
    warranty: "36-Month Warranty",
    tech: "AGM",
    fits: "Start/Stop sedans & SUVs",
    badge: "START/STOP READY",
    phone: "010 109 6211",
    imageUrl:
      "https://images.unsplash.com/photo-1635817814890-5426189b884f?auto=format&fit=crop&w=800&q=80",
  },
];

window.ABM_TEMPLATES = [
  { id: "industrial", name: "Industrial Beast" },
  { id: "modern", name: "Modern Tech" },
  { id: "editorial", name: "Editorial Grid" },
  { id: "diagonal", name: "Diagonal Slash" },
  { id: "power", name: "Power Core" },
  { id: "essentials", name: "Power Essentials" },
  { id: "dark-ui", name: "Dark Mode UI" },
  { id: "spec-sheet", name: "Spec Sheet" },
  { id: "air", name: "The Air" },
  { id: "pro", name: "The Pro" },
  { id: "widget", name: "The Widget" },
  { id: "mesh", name: "Engineered Mesh" },
];
